GRANT ALL ON SCHEMA public TO weboost_user;
GRANT ALL PRIVILEGES ON DATABASE weboost TO weboost_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO weboost_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO weboost_user;




